linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - unused
    - misspell
    - gofmt

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
